### ISSUE TITLE
New version released with old tag

### ISSUE THREAD

**Issue by winterhate** [blackmo18/kotlin-grass#16]
Hello @blackmo18 , it looks like you released new version without changing tag name (still 0.5.0). Therefore my Gradle does not detect the change in artifact repository and the new feature is not available to me or anybody who was using 0.5.0 before release.

**Comment by blackmo18** [comment]
Hi @winterhate 
at the moment i cant release any libraries for now, due to the fact that I hosted it on Jcenter. Sad to say Jcenter will no longer work starting May 1, 2021.  Below the link for any reason.

[Into the Sunset on May 1st: Bintray, JCenter, GoCenter, and ChartCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

I'll keep this open until I can migrate to maven repositories.

for the mean time, you can generate a jar file and add it to your project using `shadow jar`, it is included the project setup.

If you have any modifications made, I'll encourage to make a pull request to share it in the community.

:)

**Comment by blackmo18** [comment]
Released new version `0.6.0` at maven central
